### ISSUE TITLE
Is my sync okay?

### ISSUE THREAD

**Issue by iniTwakkie** [TheRealAlexV/proxmox-vzbackup-rclone#8]
Hi Guys,

Hope all is going well.

I have been playing around with your scripts and think I got it to work right now.

Would it be possible to look at my log file and see if all is okay?

My only question; Is the 4mb uploaded all of my CT backup? as locally it container seems to use around 1GB, so would have assume that to be uploaded. 

Please share thoughts.

INFO: starting new backup job: vzdump 102 --mode snapshot --compress zstd --remove 0 --node pve --storage Backups
INFO: Deleting backups older than 21 days.
INFO: Starting Backup of VM 102 (lxc)
INFO: Backup started at 2021-10-07 10:38:45
INFO: status = running
INFO: CT Name: docker
INFO: including mount point rootfs ('/') in backup
INFO: mode failure - some volumes do not support snapshots
INFO: trying 'suspend' mode instead
INFO: backup mode: suspend
INFO: ionice priority: 7
INFO: CT Name: docker
INFO: including mount point rootfs ('/') in backup
INFO: starting first sync /proc/1188954/root/ to /mnt/pve/Backups/dump/vzdump-lxc-102-2021_10_07-10_38_45.tmp
INFO: first sync finished - transferred 2.74G bytes in 25s
INFO: suspending guest
INFO: starting final sync /proc/1188954/root/ to /mnt/pve/Backups/dump/vzdump-lxc-102-2021_10_07-10_38_45.tmp
INFO: final sync finished - transferred 0 bytes in 3s
INFO: resuming guest
INFO: guest is online again after 3 seconds
INFO: creating vzdump archive '/mnt/pve/Backups/dump/vzdump-lxc-102-2021_10_07-10_38_45.tar.zst'
INFO: Total bytes written: 2931179520 (2.8GiB, 112MiB/s)
INFO: archive file size: 964MB
INFO: Backing up  to remote storage
INFO: rcloning /mnt/pve/pvebackups01/dump/rclone/2021/10/07
INFO: Usage:
INFO:   rclone copy source:path dest:path [flags]
INFO: Flags:
INFO:       --create-empty-src-dirs   Create empty source dirs on destination after copy
INFO:   -h, --help                    help for copy
INFO: Use "rclone [command] --help" for more information about a command.
INFO: Use "rclone help flags" for to see the global flags.
INFO: Use "rclone help backends" for a list of supported services.
INFO: Command copy needs 2 arguments minimum: you provided 1 non flag arguments: ["gdrive:/proxmox/2021/10/07"]
INFO: Finished Backup of VM 102 (00:00:57)
INFO: Backup finished at 2021-10-07 10:39:42
INFO: Backing up main PVE configs
INFO: Tar files
INFO: Compressing files
INFO: /var/tmp/proxmox-gGervNq1/proxmoxetc.2021-10-07.10.39.42.tar
INFO: /var/tmp/proxmox-gGervNq1/proxmoxpve.2021-10-07.10.39.42.tar
INFO: /var/tmp/proxmox-gGervNq1/proxmoxroot.2021-10-07.10.39.42.tar
INFO: '/var/tmp/proxmox-gGervNq1/proxmox_backup_pve.force.local_2021-10-07.10.39.42.tar.gz' -> '/mnt/pve/pvebackups01/dump/proxmox_backup_pve.force.local_2021-10-07.10.39.42.tar.gz'
INFO: rcloning /var/tmp/proxmox-gGervNq1/proxmox_backup_pve.force.local_2021-10-07.10.39.42.tar.gz
INFO: 2021/10/07 10:39:47 INFO  : proxmox_backup_pve.force.local_2021-10-07.10.39.42.tar.gz: Copied (new)
INFO: 2021/10/07 10:39:47 INFO  : proxmox_backup_pve.force.local_2021-10-07.10.39.42.tar.gz: Deleted
INFO: 2021/10/07 10:39:47 INFO  : 
INFO: Transferred:   	    4.405Mi / 4.405 MiByte, 100%, 1.467 MiByte/s, ETA 0s
INFO: Checks:                 2 / 2, 100%
INFO: Deleted:                1 (files), 0 (dirs)
INFO: Renamed:                1
INFO: Transferred:            1 / 1, 100%
INFO: Elapsed time:         4.9s
INFO: Cleaning up
INFO: Backup job finished successfully
TASK OK

**Comment by iniTwakkie** [comment]
Everything is working now :) it was the TARGET file I didnt fix yet, due to Proxmox update. FYI I also used the updated script here = https://github.com/TheRealAlexV/proxmox-vzbackup-rclone/pull/6, which also helped alot. Assume you guys can double check the script and then move into production.

**Comment by gomble** [comment]
> Everything is working now :) it was the TARGET file I didnt fix yet, due to Proxmox update. FYI I also used the updated script here = #6, which also helped alot. Assume you guys can double check the script and then move into production.

this should merged...
2 years ago

**Comment by iniTwakkie** [comment]
closing
