### ISSUE TITLE
job-abort' failed: exit code 1

### ISSUE THREAD

**Issue by jlwainwright** [TheRealAlexV/proxmox-vzbackup-rclone#9]
Hi Guys

Feel like I am missing something very simple here. Any ideas?

PVE: 7.0-13

Oct 27 21:25:01 pve systemd[1]: Finished Proxmox VE replication runner.
Oct 27 21:25:04 pve pvedaemon[32418]: INFO: Finished Backup of VM 102 (00:00:23)
Oct 27 21:25:23 pve pvedaemon[32418]: command '/root/proxmox-vzbackup-rclone/vzbackup-rclone.sh job-abort' failed: exit code 1
Oct 27 21:25:23 pve pvedaemon[1014]: <root@pam> end task UPID:pve:00007EA2:000BC0FC:6179A779:vzdump:102:root@pam: command '/root/proxmox-vzbackup-rclone/vzbackup-rclone.sh job-abort' failed: exit code 1

#!/bin/bash
# ./vzbackup-rclone.sh rehydrate YYYY/MM/DD file_name_encrypted.bin

############ /START CONFIG
dumpdir="/var/lib/vz/dump" # Set this to where your vzdump files are stored
MAX_AGE=5 # This is the age in days to keep local backup copies. Local backups >
############ /END CONFIG

# vzdump default settings

#tmpdir: DIR
#dumpdir: DIR
#storage: STORAGE_ID
#mode: snapshot|suspend|stop
#bwlimit: KBPS
#ionice: PRI
#lockwait: MINUTES
#stopwait: MINUTES
#stdexcludes: BOOLEAN
#mailto: ADDRESSLIST
#prune-backups: keep-INTERVAL=N[,...]
script:/root/proxmox-vzbackup-rclone/vzbackup-rclone.sh
#exclude-path: PATHLIST
#pigz: N

Thanks in advance

**Comment by jlwainwright** [comment]
Sorted thanks.

Changed "gd-backup_crypt:" to "ProxMox:" as that is my remote directory.

**Comment by Neokimx** [comment]
Where can I change „gd-backup_crypt“? Is it an entry in a config file?
